site_name: VLA-REPLICA Setup Guide
site_url: https://irvlutd.github.io/VLAReplica/setup/
repo_url: https://github.com/IRVLUTD/VLAReplica
theme:
  name: readthedocs
extra_css:
  - css/custom.css
nav:
  - Setup Guide:
      - Overview & prerequisites: index.md
      - Bill of materials: bill-of-materials.md
      - Hardware assembly: hardware-assembly.md
      - Software installation: software-installation.md
      - System Calibration: system-calibration.md
      - Running evaluations: running-evaluations.md
      - Task reference: task-reference.md
      - Troubleshooting & checklists: troubleshooting.md
docs_dir: setup-docs
site_dir: setup

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
